name: Build and Push Image
on:
  workflow_dispatch:

env:
  PROJECT_ID: GKE_PROJECT
  GKE_ZONE: REGION_NAME
  SERVICE: "Techhub"

jobs:
  Build and Push Image:
    name: Build and Push Image
    env:
      GKE_CLUSTER: acluster_name
    if: ${{ github.event.inputs.deploy == 'backend' && github.ref == 'refs/heads/master' || github.event.inputs.deploy == 'both' &&  github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: GKE_SA_KEY

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'

    - name: Docker login
      uses: docker/login-action@v1.14.1
      with:
        registry: ghcr.io
        username: username
        password: password

    - name: Prepare Docker
      run: |
        docker pull ghcr.io/techhub:1.0
        docker tag ghcr.io/techhuhb:1.0 ghcr.io/techhub:latest

    # Build the Docker image
    - name: Package and Build Backend
      working-directory: techhub
      run: |
        sbt docker:publishLocal
      
    # Publish the Docker image to Github Packages
    - name: Publish Docker Image to Github Packages
      run: |
        docker tag techhub-accelerators:0.1.0-SNAPSHOT ghcr.io/ghcr.io/techhub:1.0
        docker push ghcr.io/ghcr.io/techhub:1.0
        docker push ghcr.io/ghcr.io/techhub:latest
